name: 哔哩哔哩签到

on:
    workflow_dispatch:
    schedule:
        - cron: "5 16 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: "Set up Python"
              uses: actions/setup-python@v1
              with:
                python-version: 3.8

            - name: "安装依赖包"
              run: pip install -r ./requirements.txt

            - name: "运行 哔哩哔哩签到"
              run: python3 function/bilibili.py
              env:
                  BILI_USER: ${{ secrets.BILI_USER }}
                  BILI_PASS: ${{ secrets.BILI_PASS }}
                  BILI_COOKIE: ${{ secrets.BILI_COOKIE }}
                  BILI_NUM: ${{ secrets.BILI_NUM }}
                  BILI_TYPE: ${{ secrets.BILI_TYPE }}
                  SEND_KEY: ${{ secrets.SEND_KEY }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  QQ_SKEY: ${{ secrets.QQ_SKEY}}
                  QQ_MODE: ${{ secrets.QQ_MODE}}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
#最后推送 2021年1月15日